### ISSUE TITLE
Lightweight user research with first-time interviewer 

### ISSUE THREAD

**Issue by alexsobledotgov** [18F/eng-hiring#147]
Ask a first-time interviewer to read through the guides and flag/highlight anything that is unclear, inconsistent, or otherwise raises a flag.

**Comment by SSPJ** [comment]
I found the guides very easy to read and follow.

The one thing which was not clear to me while reading the [overview page](https://eng-hiring.18f.gov/) was the purpose of the individual interview guide pages ([technical](https://eng-hiring.18f.gov/interviews/technical/), etc). Although they are linked to from within Step 5 of the section entitled "Step-by-step process", I expected that they linked to definitions.

Since I already knew what each of those interviews were, I missed clicking through and discovering that they _also_ contained instructions and links to internal 18F documents.

I guess that's a long way of saying that a small sitemap on the first page of the guide would be pretty handy. 😄

**Comment by alexsobledotgov** [comment]
Thank you @SSPJ! Belatedly broke this feedback into its own ticket #159!
