### ISSUE TITLE
Take #2 -- testing, testing ... integration with DA team project board #152

### ISSUE THREAD

**Issue by alexsobledotgov** [18F/eng-hiring#156]

**Comment by alexsobledotgov** [comment]
https://github.com/18F/eng-hiring/actions/runs/4378046792

```
Run actions/add-to-project@v0.4.0
  with:
    project-url: https://github.com/orgs/18F/projects/41
    github-to***en: ***
    labeled: da-team
    label-operator: AND
Error: Request failed due to following response errors:
 - Could not resolve to a ProjectV[2](https://github.com/18F/eng-hiring/actions/runs/4378046792/jobs/7662283274#step:3:2) with the number [4](https://github.com/18F/eng-hiring/actions/runs/4378046792/jobs/7662283274#step:3:4)1.```

**Comment by alexsobledotgov** [comment]
@mgwalker, have you seen this error before setting up DA project board integrations for other repos?

**Comment by mgwalker** [comment]
No but I'm 90% sure it's because the token isn't getting the permissions it needs. It's being scoped down to `issue: write`, which is not sufficient. There's not really any good reason to scope it down at all (and I don't think there's a scope in GitHub's permissions hierarchy for v2 projects yet anyway). If all it needed was issue write permissions, we could have just used the action's default token.

**Comment by alexsobledotgov** [comment]
@mgwalker — I see, I'll try removing that scope and let's see if it works.
